# Generated by Django 4.0.4 on 2022-05-10 14:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0003_reasontype_alter_premiumgrid_tariff_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to='doc_templates/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Incoming document',
                'verbose_name_plural': 'Incoming documents',
            },
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('number', models.IntegerField(verbose_name='Identifier')),
                ('date', models.DateField(verbose_name='Date')),
                ('file', models.FileField(upload_to='generated_docs/', verbose_name='File')),
                ('reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.reasontype', verbose_name='Reason')),
            ],
            options={
                'verbose_name': 'Output document',
                'verbose_name_plural': 'Output documents',
            },
        ),
    ]
