# Generated by Django 4.0.4 on 2022-05-18 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_premiumgrid_tariff_category_and_more'),
        ('military_unit', '0004_remove_staff_military_unit_and_more'),
        ('docs', '0002_doctemplate_created_at_doctemplate_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'ordering': ['-created_at'], 'verbose_name': 'Output document', 'verbose_name_plural': 'Output documents'},
        ),
        migrations.RenameField(
            model_name='docs',
            old_name='number',
            new_name='document_number',
        ),
        migrations.RemoveField(
            model_name='docs',
            name='name',
        ),
        migrations.AddField(
            model_name='docs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='docs',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='military_unit.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='docs',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.position', verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='docs',
            name='template_document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.doctemplate', verbose_name='Incoming document'),
        ),
        migrations.AddField(
            model_name='docs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
