# Generated by Django 4.0.4 on 2022-05-20 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_premiumgrid_tariff_category_and_more'),
        ('docs', '0003_alter_docs_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='general.reasontype', verbose_name='Reason Type'),
        ),
    ]
