# Generated by Django 4.0.4 on 2022-05-10 13:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_militaryrank_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReasonType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Reason Type',
                'verbose_name_plural': 'Reason Types',
            },
        ),
        migrations.AlterField(
            model_name='premiumgrid',
            name='tariff_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_grid', to='general.tariffcategory', verbose_name='Tariff Category'),
        ),
        migrations.AlterField(
            model_name='tariffgrid',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_grid', to='general.position', verbose_name='Position'),
        ),
    ]
