# Generated by Django 4.0.4 on 2022-04-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='streetaddress',
            options={'verbose_name': 'Street Address', 'verbose_name_plural': 'Street Addresses'},
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='streetaddress',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street_addresses', to='common.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='streetaddress',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Street name'),
        ),
    ]
