# Generated by Django 4.0.4 on 2022-04-17 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='common.streetaddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=3)),
                ('birth_date', models.DateField()),
                ('family_status', models.CharField(max_length=255)),
                ('children_number', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('tin', models.CharField(max_length=15)),
                ('length_of_service', models.PositiveIntegerField()),
                ('contract_term', models.PositiveIntegerField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='common.streetaddress')),
                ('military_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='general.militaryrank')),
                ('military_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='general.militaryspecialization')),
                ('recruitment_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_persons', to='military_unit.militaryunit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('inner_military_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.militaryrank')),
                ('military_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='military_unit.militaryunit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='military_unit.person')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.tariffgrid')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
