# Generated by Django 4.0.4 on 2022-04-13 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('military_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.militaryrank')),
                ('military_specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.militaryspecialization')),
                ('military_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='military_unit.militaryunit')),
                ('staff_military_rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_inner_staff', to='general.militaryrank')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.tariffgrid')),
            ],
        ),
    ]
