# Generated by Django 4.0.4 on 2022-04-29 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_militaryrank_options_and_more'),
        ('common', '0002_alter_city_options_alter_streetaddress_options_and_more'),
        ('military_unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='militaryunit',
            options={'verbose_name': 'Military Unit', 'verbose_name_plural': 'Military Units'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Persons'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
        migrations.AddField(
            model_name='militaryunit',
            name='military_number',
            field=models.IntegerField(default=1, verbose_name='Identifier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='general.position'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='militaryunit',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_units', to='common.streetaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='militaryunit',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='common.streetaddress', verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='person',
            name='children_number',
            field=models.PositiveIntegerField(verbose_name='Children number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='contract_term',
            field=models.PositiveIntegerField(verbose_name='Contract term'),
        ),
        migrations.AlterField(
            model_name='person',
            name='family_status',
            field=models.CharField(max_length=255, verbose_name='Family status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=3, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='length_of_service',
            field=models.PositiveIntegerField(verbose_name='Length of service'),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(max_length=255, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='general.militaryrank', verbose_name='Military rank'),
        ),
        migrations.AlterField(
            model_name='person',
            name='military_specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='general.militaryspecialization', verbose_name='Military specialization'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='recruitment_office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_persons', to='military_unit.militaryunit', verbose_name='Recruitment office'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tin',
            field=models.CharField(max_length=15, verbose_name='TIN'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='inner_military_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.militaryrank', verbose_name='Inner military rank'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='military_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='military_unit.militaryunit', verbose_name='Military unit'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_role', to='military_unit.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_unit_staff', to='general.tariffgrid', verbose_name='Tariff'),
        ),
    ]
