# Generated by Django 4.0.4 on 2022-05-16 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_premiumgrid_tariff_category_and_more'),
        ('military_unit', '0003_alter_militaryunit_military_number_personnel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='military_unit',
        ),
        migrations.AddField(
            model_name='militaryunitinfo',
            name='chief_rank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chief rank'),
        ),
        migrations.AddField(
            model_name='militaryunitinfo',
            name='commander_rank',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commander rank'),
        ),
        migrations.AddField(
            model_name='staff',
            name='military_registration_specialty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='general.militaryspecialization', verbose_name='Military Specialization'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='general.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='inner_military_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='general.militaryrank', verbose_name='Military Rank'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='military_unit.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='general.tariffgrid', verbose_name='Tariff'),
        ),
        migrations.DeleteModel(
            name='Personnel',
        ),
    ]
