# Generated by Django 4.0.4 on 2022-05-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_unit', '0005_person_cash_payments_person_military_unit_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='family_status',
            field=models.CharField(choices=[('одружений', 'одружений'), ('неодружений', 'неодружений'), ('заміжня', 'заміжня'), ('незаміжня', 'незаміжня'), ('розлучений', 'розлучений'), ('розлучена', 'розлучена'), ('вдова', 'вдова'), ('вдівець', 'вдівець')], max_length=255, verbose_name='Family status'),
        ),
        migrations.AlterField(
            model_name='person',
            name='type_of_contract',
            field=models.CharField(choices=[('мобілізація', 'мобілізація'), ('строкова служба', 'строкова служба'), ('контракт', 'контракт')], max_length=100, verbose_name='Type of contract'),
        ),
    ]
