# Generated by Django 4.0.4 on 2022-05-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_premiumgrid_tariff_category_and_more'),
        ('military_unit', '0006_alter_person_family_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='general.position', verbose_name='Position'),
        ),
    ]
